services:
  - docker

before_install:
  - docker build --pull -t build_image .

script:
  - docker run --volume "$(pwd)/iso:/build/result/iso" --volume "$(pwd)/configuration.nix:/build/configuration.nix" --rm -it build_image
